#21 Added Membercards and added Doc
mnaray/USG_Website pull request #66
Opened 2022-10-14 10:29 UTC by h0peRL

I added both Membercard.tsx and MembercardGrid.tsx and added the Documentation for them.

2022-10-14 12:16 UTC, mnaray requested changes
Bitte diese Komponenten jeweils unter **_Komponenten_** dokumentieren und nicht unter "unsichtbar".

Unter anderem würde ich ggf. die Membercard-Komponente beim MemberGrid referenzieren (**bitte nur den Index und nicht das File**❗), damit dem Leser klarer ist, was genau wir tabular darstellen möchten.

Die Idee mit den Properties finde ich ganz kreativ. Eventuell überarbeiten wir mal die Doku aller Komponenten, welche props haben. Das sieht ästhetisch und übersichtlich aus. 👍

2022-10-14 14:26 UTC, h0peRL commented
@mnaray i just edited your reviwes. Approve again please.

2022-10-24 14:03 UTC, h0peRL commented
In Ordnung, ich werde meine Dokumentation in ein txt file machen und im doc Ordner ablegen.

2022-10-25 19:14 UTC, mnaray commented
Bitte Konflikte vollständig lösen.

2022-10-26 09:30 UTC, mnaray approved these changes
Sieht jetzt wieder gut aus

2022-10-26 09:30 UTC, merged